### ISSUE TITLE
Get use cases

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/research-data-harvester#1]
@windcowles has some to provide.

**Comment by windcowles** [comment]
Link to google doc with initial list: https://docs.google.com/document/d/1qFIYMYHSHorNFjjrkqEtDQyVFAtiz3ZFv2CrRv3QNw0/edit

**Comment by hackartisan** [comment]
Thanks @windcowles! I used this list plus notes from our conversation last week to create issues #5, #6, #7, #8, #9.
