### ISSUE TITLE
Research and Document harvesting from OpenNeuro

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/research-data-harvester#12]
OpenNeuro (openeuro.org) - A domain-specific repository that I know several of our neuroscience researchers use
Here are a couple datasets from Princeton researchers:
https://openneuro.org/datasets/ds001131/versions/1.0.0
https://openneuro.org/datasets/ds002345/versions/1.0.1

Document in wiki:
* What endpoints do they offer?
* What data fields do they provide?
* What standards do they support?

**Comment by hackartisan** [comment]
@windcowles similar question here, were you able to retrieve those datasets by searching for Princeton? I did a keyword search for Princeton (not really ideal; could have a high false-positive rate) and turned up just this one https://openneuro.org/datasets/ds000223/versions/00001

From looking at the records it doesn't seem that this repository records institutional affiliation so I'm not sure how we would harvest these records. I did get a response from support so will follow up with them.

**Comment by windcowles** [comment]
For this one I think I cheated and just searched by a faculty member that I knew had data in Open Neuro. There are at least two labs at PU that use it pretty actively.

**Comment by hackartisan** [comment]
Okay I've looked at their api and I've spoken to their support person. They don't store institutional affiliation and I don't see any other identifiers associated with their users. If we wanted to impose a requirement that some admin user enters some bit of data, I think we could make this work if we had one of the following:

* an openneuro dataset id (e.g. ds001131) - we could directly query graphql for that object
* a doi for the associated article - we could page through all datasets via graphql and look for the one with the right doi
* an openeuro user id (e.g. 7c2ffc11-d665-4bf1-850a-2ae06a02dd1f) for the person who uploaded the dataset - we could page through all datasets via graphql and look for the one with the right uploader

**Comment by hackartisan** [comment]
Additional info obtained by emailing their support (corresponded with Franklin):

* GraphQL: We use a GraphQL API endpoint that you can submit queries to. We recently spun up a [docs](https://docs.openneuro.org/api) for more information regarding our infrastructure. Currently a WIP but is a good starting place. Our API follows the Relay spec - https://relay.dev/docs/en/graphql-server-specification.html - for constructing requests.
  * Looking at the graphql documentation I don't see a way to get institutional affiliation -- see above comment for potential not-fully-automated ways forward.
* Google Sheets: Depending on the type of metadata you are looking for we also have a public metadata sheet (http://metadata.openneuro.org) that captures several fields. This is maintained by the OpenNeuro team. 
  * I looked at this and it does not include institutional affiliation. It does not include anything that the graphql endpoint doesn't already have.
