### ISSUE TITLE
Research and Document harvesting from NIMH Data Archive

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/research-data-harvester#13]
NIMH Data Archive (nda.nih.gov) - One of several required repositories that NIH hosts for data generated from NIH-funded projects. This is one that I know has a least some Princeton-generated data. This is a different kind of repo because it includes additional information re: funding and other relevant project data. If it's too much of an odd duck, we could leave it until another round.
Here is a dataset from a Princeton researcher: https://nda.nih.gov/edit_collection.html?id=2521

Document in wiki:
* What endpoints do they offer?
* What data fields do they provide?
* What standards do they support?

**Comment by hackartisan** [comment]
@windcowles I am unable to discover the record you posted by searching for "Princeton" -- I'm not sure the grant information / organization field is indexed. How did you find this record?

**Comment by windcowles** [comment]
I selected "data by lab", and there is a drop-down menu for institutions there, where I selected Princeton
![image](https://user-images.githubusercontent.com/48189647/82372883-c41f3d00-99ea-11ea-9b32-49701396de24.png)

**Comment by hackartisan** [comment]
Corresponded with help desk (David Obenshain). The organization field is not searchable from the API. He sent an example result searching by grant number. From the fields returned it doesn't look like there's anything that can help us here. I've asked for more details but unfortunately it looks like we're in a situation similar to OpenNeuro: unless we have a step where someone inputs a record id we won't be able to pull metadata from this repository. Even then it might not be entirely reliable, since there doesn't seem to be a way to limit the query to a specific field. The grant number would probably be the most reliable identifier, since their record id is just an integer.

Here's the info I received (there was a problem with the api via the swagger ui, which he refers to at the end):

```
You could try a request using cURL for example:
curl --location --request POST 'https://nda.nih.gov/api/search/nda_sw_removal/collection/full' \
--header 'Content-Type: text/plain' \
--data-raw 'Princeton'
This returns no search results, as organization is not one of the attributes we currently expose for search from within the search API. 

We do, however, support query by grant number, which will return the collection associated with this grant.
curl --location --request POST 'https://nda.nih.gov/api/search/nda_sw_removal/collection/full' \
--header 'Content-Type: text/plain' \
--data-raw 'R01MH112566'

Here is the result from this web service request:
{
 "study": {
 "total": 0,
 "results": []
    },
 "experiment": {
 "total": 0,
 "results": []
    },
 "concept": {
 "total": 0,
 "results": []
    },
 "publication": {
 "total": 0,
 "results": []
    },
 "datastructure": {
 "total": 0,
 "results": []
    },
 "datadict": {
 "total": 0,
 "results": []
    },
 "collection": {
 "total": 1,
 "results": [
            {
 "pi_list": "Uri Hasson",
 "phase": "Enrolling",
 "overview": "Social interaction in real-life contexts necessitates dynamical interactions among two or more brains as individuals listen, speak, act, and mutually adapt to one another to reach shared understanding. Elucidating how brains forge such shared understanding requires shifting from a one-brain to a multiple-brain frame of reference, as well as from artificial laboratory conditions to natural, real-life settings. Here we outline a novel framework to identify inter-brain dynamical coupling that underpins knowledge about social phenomena e.g.,mental states, social norms, emotions, etc., henceforth referred to as social knowledge. The long-term goal of our laboratories is to understand how neural networks couple, within and across brains, to create and share information that enables social understanding and connectedness. We intend to develop a novel brain-to-brain coupling framework to better understand how social concepts are represented in the brain and how they are transferred across brains to achieve group cohesiveness. The overall objective of this application is to identify mechanisms that facilitate coupling across a speaker and a listener during real life interaction. This approach is innovative because it uses new experimental paradigms optimize for studying social interactions in naturalistic contexts, employs both fMRI and fNIRS methods single scanning and hyperscanning, and includes development of novel analysis methods for modeling shared brain responses to complex, natural social stimuli in real-life contexts. This contribution is significant because the proposed research will provide new insights into a central function of the human brain the ability to connect with others by dynamically and interactively creating and sharing social knowledge. The work proposed in this application will advance knowledge of how brains process and share information in ways that promote social understanding and will produce new approaches for detecting and diagnosing communication and developmental disorders.",
 "id": "2611",
 "_score": 6.417647,
 "title": "Brain-to-brain dynamical Coupling: A New framework for the communication of social knowledge",
 "grantNumber": "R01MH112566"
            }
        ]
    },
 "content": {
 "total": 0,
 "results": []
    }
}

I have tagged this ticket as a user story for our search API, for future consideration, and we will correct the swagger configuration.
```

**Comment by hackartisan** [comment]
Regarding the error I was getting from the swagger UI, here's the relevant Q/A (for posterity):

---
Hello,

We’re starting a project to harvest metadata about datasets from Princeton University researchers from different data repositories.

I’m looking at your API documentation and I hope you can help me with some questions.

First, is the search API the best way to harvest metadata? I.e. do you offer any other harvesting services or endpoints such as OAI-PMH?

Second, the documentation [1] states that the search api does not require authentication. But when I try it out on the swagger ui [2] it returns a 401 Unauthorized code [3]. Do I actually need authentication or is there a bug with the swagger ui?

Finally, in the UI when I go to “Get Data” > “Data from Labs” I can select “Princeton University” in the “Organization” field to get the results I’m interested in. How can I replicate that search with the API? I’m not sure what querystring parameters to use since they don’t appear in my url when I submit the form.

Thanks so much for your help,
Anna

[1] https://nda.nih.gov/tools/apis.html
[2] https://nda.nih.gov/api/search/docs/swagger-ui.html#!/search/searchUsingPOST_1
[3]
```
 {
"timestamp": 1589995033017,
"status": 401,
"error": "Unauthorized",
"message": "Full authentication is required to access this resource",
"path": "/api/search/api/search/nda/%7Btypes%7D/full"
}
```

---
Hello Anna,

There is an error in the swagger user interface configuration, it currently has a property set for base url of 
[ base url: /api/search/api/search ]

The API does have protected non-public endpoints, and the configuration requires authentication for any requests that aren't for public-facing endpoints whether they are exist or not. That is reason you are getting the 401 unauthorized response.

...(the rest of the response is in the comment above)

**Comment by hackartisan** [comment]
I'll update this if I get any more info from them, but I'm going to go ahead and close.

**Comment by hackartisan** [comment]
Last exchange:

Hi David,

Thanks for this info, and for considering our use case. I’m wondering what other fields are exposed for search by your search API. Are these documented, or could you provide a list?

Is it possible to provide the field to search, or would it just be a general search over all exposed fields? A fielded search would help avoid false matches if, for some reason the word were mentioned in some other context.

If organization is not exposed I’m not sure whether we’ll be able to do this harvesting, but it would be helpful to know what our other options are.

Finally, can you help me understand the difference between nda, nds_sw_removal, and nda_auto_comp? I’m not sure how these indices differ.

---
It will take a bit of time to assemble this from wiki documentation, the fields enabled for search are not documented in swagger. 

Search is over all fields, you can limit by type, but not at field level. The indexes nda, nda_sw_removal, and nda_auto_comp represent standard lucene index, index with stop words removed, and index to support auto-completion (type ahead) as you enter text into the search field. The search api was built to support NDA site-wide search, so features are pretty specific to it.

It will take some investigation to see if there is some other automated method you could follow to harvest the information you are looking for, but this isn't a use case we support in services that we have available.

If your researchers have published and followed guidance from NDA to create studies (https://ndar.nih.gov/data_from_papers.html), these will be available from DataCite as each have an DOI associated with them. When we generate DOIs, we link the NDA Study DOI with the journal article's DOI (if available) at the time of DOI registration. You may be interested in DataCite's event data to harvest any studies that have been registered in NDA related to publications by Princeton Researchers. https://datacite.org/eventdata.html

David
NDA Help Desk
