### ISSUE TITLE
Research and Document Harvesting from DataVerse

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/research-data-harvester#14]
DataVerse (dataverse.harvard.edu) -- A Harvard developed domain-general repository that is distributed, with Harvard as the central hub. Many Princeton researchers use this one.

Here are a couple datasets from Princeton researchers:
https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/1FUZ0S
https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/HTMX3K

Document in wiki:
* What endpoints do they offer?
* What data fields do they provide?
* What standards do they support?

**Comment by hackmastera** [comment]
@windcowles documentation frequently references "your dataverse". We don't intend to have our own dataverse? Just use the harvard one?

**Comment by hackartisan** [comment]
I think we might need to create our own dataverse in order to create a set to use for oai-pmh harvesting.

Edit: That wasn't true; Harvard created a set for us to use to access their dataverse.

**Comment by hackartisan** [comment]
Harvard Dataverse created a set for us to use in harvesting via OAI. There's currently a metadata issue where some special characters are resulting in invalid xml but we've written a harvester that works with a different set and filled in the metadata fields matrix using that sample data, as well. Documentation at https://github.com/pulibrary/research-data-harvester/wiki/Repositories#dataverse
