### ISSUE TITLE
Research and document harvesting from Dimensions

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/research-data-harvester#20]
PUL has a subscription to a product from Digital Science called Dimensions. (https://library.princeton.edu/resource/40379) which has at least some published datasets in it. It might be a source of dataset metadata.

Need to look into API access. The website allows you to search for PU researchers and then see their pubs and datasets.

**Comment by eliotjordan** [comment]
Sent a feedback support message to request more information on generating an access token for the Dimensions API. Not sure our accounts have this feature enabled or how to generate the token since it requires a "password" and we log in via CAS.

https://docs.dimensions.ai/dsl/api.html#api-access

**Comment by eliotjordan** [comment]
I generated a token and put it in LastPass in `dimensions_api_token`.

**Comment by eliotjordan** [comment]
Query for publications will be something like:

```
search publications where research_org_names ="Princeton University" or research_orgs="grid.16750.35" return publications[all]
```

and datasets:
```
search datasets where research_orgs="grid.16750.35" return datasets[all]
```

The response is verbose("all"), but that can be tailored. Next step is to figure out paging.

**Comment by eliotjordan** [comment]
For paging, use `limit` for page size and `skip` for offset.

```
search datasets where research_orgs="grid.16750.35"
return datasets[all] limit 100 skip 100
```

Total record count is returned in each request in the `_stats` property:

```
 "_stats": {
        "total_count": 1916,
        "limit": 100,
        "offset": 100
    }
```
