### ISSUE TITLE
Get data standard documentation

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/research-data-harvester#3]

**Comment by windcowles** [comment]
There are lots of different metadata standards for research data; the PDCOG had talked about the merits of picking a core (Dublin, DataCite/DDI, etc.) and then adding domain-specific extensions as needed. For harvesting, there's a standard, OAI-PMH, that archives use that data repositories also (sometimes, often?) use. (https://www.openarchives.org/pmh/)

**Comment by windcowles** [comment]
Some other notes from OAI-PMH discussions with Esmé, Annalise, and Jon, in case they are helpful: 
- Over a decade old - longstanding library standard
- Set of verbs for interacting with repository collections and content
- Widely supported
- Makes a baseline recommendation of Dublin Core metadata (1.1, not DCTerms). Implementers can use additional formats like MARC. 
- Dublin Core is wide open as a metadata form. Presents some challenges when we begin harvesting data.
- We can choose to set our own baseline requirements for what metadata our repository. 
- Other protocols, OAI-ORE (Object Reuse and Exchange) - U of M, resourcesync
- Archive-It software supports API. 
- We should be prepared to write connectors for repositories that may not support a standard harvesting protocol. 
- SWORD is a protocol for depositing items into a repository
- CDL uses OAI-PMH

**Comment by hackartisan** [comment]
👍 thank you!
