### ISSUE TITLE
Produce initial list of fields we hope to collect

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/research-data-harvester#4]
@windcowles should be able to provide a list

Also several of the issues labeled "user story" reference specific data desired for search or display.

Let's list them on the wiki: https://github.com/pulibrary/research-data-harvester/wiki/Database

**Comment by hackartisan** [comment]
@windcowles I've created an initial list at https://github.com/pulibrary/research-data-harvester/wiki/database - could you look over it and let me know in the comments of this issue whether anything there should be removed?

Also, I think you mentioned you had the beginning of a list somewhere, or were you referring to the use cases document? I pulled from the use cases already, but if there's some other list feel free to paste it in a comment here.

Once I've started hitting actual endpoints I'll try to create a table of fields and what they're labeled as in the various repositories.

**Comment by windcowles** [comment]
I don't have a list for this, so I'm glad you started this up. I think this covers the cases that I can think of. I'm not sure that we need both 'date created' and 'date deposited' - can we think of cases  where it would be important to know date created (vs. date deposited)? I think we do want to get all of the author/creator/contributors that we can; authorship for data can be tricky and I don't want us to accidentally misrepresent by only having the Princeton person.

**Comment by hackartisan** [comment]
@windcowles I included both dates because imagined scenarios like:

* Dataset creation and deposit were separated by a large span of time (e.g. it sat around on a hard drive for 15 years and then was deposited, long after the related paper was published)
* Dataset was created / deposited, then reviewed and corrected or updated at a later time and then deposited again.

For now I'll change it to just say "date". This may be more realistically what we end up with, assuming there's variation on what repositories provide.
